### ISSUE TITLE
No DB migration

### ISSUE THREAD

**Issue by mzch** [diced/zipline#77]
I installed v3.0 and run `yarn install` and `yarn build`, then `yarn start`.
But DB tables aren't created.
Is this bug?

**Comment by TheRealHeyJack** [comment]
try running `yarn create-all-migrations`

**Comment by mzch** [comment]
I got an error:
```javascript
yarn run v1.22.5
warning package.json: No license field
$ node scripts/create-migrations
node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir './prisma/migrations'
    at readdirSync (node:fs:1380:3)
    at getFirstDir (/srv/zipline/zipline/scripts/create-migrations.js:13:17)
    at createPSQLMigrations (/srv/zipline/zipline/scripts/create-migrations.js:21:15)
    at Object.<anonymous> (/srv/zipline/zipline/scripts/create-migrations.js:40:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: './prisma/migrations'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by diced** [comment]
the create-all-migrations command is supposed to be run in development environments. Could you show your config/env variables for the first issue?

**Comment by mzch** [comment]
My `config.toml` is:

```toml
[core]
secure = true
secret = 'secret
host = '127.0.0.1'
port = 8000

[database]
# postgresql
type = 'psql'
url = 'postgres://zipline:password@127.0.0.1:5432/zipline'

# mysql
# type = 'mysql'
# url = 'mysql://postgres:postgres@mysql/mysql'

# sqlite
# type = 'sqlite'
# url = 'file:sqlite.db'

[uploader]
route = '/u'
embed_route = '/a'
length = 6
directory = '/srv/zipline/files'
```
